// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bogsy_video_store.Data;

#nullable disable

namespace bogsy_video_store.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250718054658_added isReturned in rentals")]
    partial class addedisReturnedinrentals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("bogsy_video_store.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("bogsy_video_store.Entities.RentalEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("customer_id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isReturned")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("overdue_price")
                        .HasColumnType("float");

                    b.Property<DateTime>("rent_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("rent_days")
                        .HasColumnType("int");

                    b.Property<DateTime>("return_date")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("total_price")
                        .HasColumnType("float");

                    b.Property<Guid>("video_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("customer_id");

                    b.HasIndex("video_id");

                    b.ToTable("rentals");
                });

            modelBuilder.Entity("bogsy_video_store.Entities.VideoEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("rent_days")
                        .HasColumnType("int");

                    b.Property<string>("video_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("video_price")
                        .HasColumnType("float");

                    b.Property<string>("video_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("videos");
                });

            modelBuilder.Entity("bogsy_video_store.Entities.RentalEntity", b =>
                {
                    b.HasOne("bogsy_video_store.Entities.CustomerEntity", "customer")
                        .WithMany("rentals")
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bogsy_video_store.Entities.VideoEntity", "video")
                        .WithMany("rentals")
                        .HasForeignKey("video_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("video");
                });

            modelBuilder.Entity("bogsy_video_store.Entities.CustomerEntity", b =>
                {
                    b.Navigation("rentals");
                });

            modelBuilder.Entity("bogsy_video_store.Entities.VideoEntity", b =>
                {
                    b.Navigation("rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
